# Generated by Django 5.1.3 on 2024-12-16 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeltesting', '0003_album_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='language',
        ),
    ]
