# Generated by Django 5.1.3 on 2024-12-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltesting', '0004_remove_album_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('H', 'Hindi'), ('G', 'Gujarati')], default='E', max_length=1),
        ),
    ]
