# Generated by Django 5.1.3 on 2024-12-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltesting', '0005_album_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='pktesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
