# Generated by Django 5.1.3 on 2024-12-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltesting', '0006_pktesting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pktesting',
            name='id',
        ),
        migrations.AlterField(
            model_name='pktesting',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
