# Generated by Django 5.1.3 on 2024-12-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltesting', '0007_remove_pktesting_id_alter_pktesting_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pktesting',
            name='name',
        ),
        migrations.AddField(
            model_name='pktesting',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pktesting',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='pktesting',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='pktesting',
            name='password',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='pktesting',
            name='username',
            field=models.CharField(default='', max_length=25),
        ),
    ]
