# Generated by Django 5.1.3 on 2024-12-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeltesting', '0008_remove_pktesting_name_pktesting_age_pktesting_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='pktesting',
        ),
    ]
