# Generated by Django 5.1.3 on 2024-12-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modeltesting', '0009_testing_delete_pktesting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testing',
        ),
    ]
